<?php
/**
 * @var Complex\My\Block\Article $block
 */
?>

<?php $article = $block->view(); ?>

<?php if( $article = $block->view() ): ?>
    <div>
    <strong><?php echo "Authors name: "; echo $article->getAuthor(); ?></strong>
    <span><?php echo $block->getFormatDate($article->getCreatedAt()); ?></span>
    </div>
    <h3><?php echo "Title: "; echo $article->getTitle(); ?></h3>

    <?php if( $article->getContent() ): ?>
        <p><?php echo "Content: "; echo $article->getContent(); ?></p>
    <?php else: ?>
        <p><?php echo "Description: "; echo $article->getDescription(); ?></p>
    <?php endif; ?>
<?php endif; ?>
