<?php
/**
 * @var Complex\My\Block\Main $block
 */
?>

<form action="/complex/comment/redirect" method="get">
    <p>Input author
        <input type="text" name="author">
    </p>
    <p>Input title
        <input type="text" name="title">
    </p>
    <p>Input description
        <textarea
            name="description">
        </textarea>
    </p>
    <p>Input content
        <textarea
            name="content">
        </textarea>
    </p>
    <p>Check status
        <input type="checkbox" name="status">
    </p>
    <p>Check enabled
        <input type="checkbox" name="enabled">
    </p>
    <button
        type="submit" value="Submit">Submit
    </button>
</form>

